### ISSUE TITLE
Online video 2 MP3

### ISSUE THREAD

**Issue by SylvainDe** [apfeltee/a2mp3#1]
Hi,

I haven't tested your tool yet but I have a suggestion corresponding to a scenario I'm facing every now and then  : getting the mp3 for a video from an online video provider (Youtube, Dailymotion, etc).

A few websites do this already : www.youtube-mp3.org/ convert2mp3.net/en/ www.flvto.biz/ www.vidtomp3.com/ and so many others. It could be nice to have this integrated in the CLI from your tool.

**Comment by SylvainDe** [comment]
I'll try to add a PR this week.

Note to myself :http://askubuntu.com/questions/178481/how-to-download-an-mp3-track-from-a-youtube-video

**Comment by apfeltee** [comment]
There's no need for that, actually; [youtube-dl](https://rg3.github.io/youtube-dl/) not only supports extracting sound directly, it also supports a _lot_ of video hosting sites (in spite of its name).
